#!/usr/bin/env bash
# Emits embedded_data.ml on stdout: every bundled (symbol, date) CSV under
# data/, plus the demo alpha, baked into the client so the browser app
# needs no server or filesystem. Run by the dune rule in this directory.
# (Adapted from app/ui/client/gen_embedded_data.sh.)
set -euo pipefail

data_dir="$1"
demo_alpha="$2"

echo "(* Generated by gen_embedded_data.sh — do not edit. *)"
echo "let files : (string * string * string) list ="
echo "  ["
for sym_dir in "$data_dir"/*/; do
  sym=$(basename "$sym_dir")
  if [ "$sym" = "raw" ]; then continue; fi
  for f in "$sym_dir"*.csv; do
    date=$(basename "$f" .csv)
    printf '    ( "%s"\n    , "%s"\n    , {___|' "$sym" "$date"
    cat "$f"
    printf '|___} )\n  ;\n'
  done
done
echo "  ]"
echo ";;"
printf 'let demo_alpha = {___|'
cat "$demo_alpha"
printf '|___}\n'
